---
title: "_Ashwini_Choudhary_Partial_Test"
output: html_document
date: "2022-12-01"
---

```{r}
library(tidyverse)
library(dplyr)

rd<- read.delim("UKLifeExpectancy.tsv")

```

```{r}
#1 Dimension of data
dim(rd)
```

```{r}
#2 Type of Data
typeof(rd)
```

```{r}
#3 Descriptive statistics of data
summary(rd)
```

```{r}
#Question4 Male life Expectancy rate over the years
ggplot(rd,aes(x= Year,y=Male.Life.Expectancy)) + geom_point() 
```

```{r}
#Question 5 Barplot for the Male Expectancy
ggplot(rd,aes(x=Male.Life.Expectancy,color=Male.Life.Expectancy))+geom_bar(aes(fill=Male.Life.Expectancy))

#As comparing to the question 4 scatter plot is better way to visualize the data.

```
```{r}
#Question6 Realtionship b/w male and female life expectancy
ggplot(rd,aes(x=Male.Life.Expectancy,y=Female.Life.Expectancy)) + geom_point() 
```
```{r}

#Q7 Replot the male and female expectancy with straight line with intercept 0 and slope 1
ggplot(rd,aes(x=Male.Life.Expectancy,y=Female.Life.Expectancy))  +geom_point()+geom_smooth(method = "lm", se = FALSE)
```
```{r}
#Q8

plot(rd$Year, rd$Female.Life.Expectancy, type='l', col='red')
lines(rd$Year,rd$Male.Life.Expectancy,type='l',col='blue')

legend("topleft", legend=c("Female", "Male"),
       col=c("red", "blue"), lty = 1:1)

# when I used the point function it was showing the scatter plot which was according to me not data visualization friendly I could not derive information or result from it that's why I used the LINE function to plot in line format to compare the easily
```
```{r}
#Q9 select Column starting with Y
rd %>% select(starts_with('Y'))
```
```{r}
#10 Move female expectancy column before the male expectancy
rd %>% relocate(Female.Life.Expectancy, .before =Male.Life.Expectancy )
```
```{r}
#11 Select all column except Annotation
rd %>% select(1:3)
```
```{r}
#Question12
rd %>% select(Year, Male.Life.Expectancy)%>%filter(Male.Life.Expectancy>50)

#EXPLANATION:Here I've showed all the years in which male expectancy was greater than 50 in the next cells I'm showing the total number of years where male life expectancy was more then 50
```
```{r}
#Q12 Total number of years where male expectancy was greater then 50

rd %>% select(Year, Male.Life.Expectancy)%>%filter(Male.Life.Expectancy>50) %>%
  summarise(n_distinct(Year))
```
```{r}
#Q13 Male Life expectancy in 1956

rd %>% select(Year,Male.Life.Expectancy) %>% filter(Year=='1956')
```
```{r}
#14Q Female expectancy equal to 74.96 in which year?
rd %>% select(Year,Female.Life.Expectancy) %>% filter(Female.Life.Expectancy=='74.96')
```
```{r}
#15 adding 20th Century column with true and false value
rd<-rd %>% 
  mutate(century20th = if_else(Year>=1900 & Year<=2000, "TRUE", "FALSE"))
rd
```
```{r}
#Q16 Subset the value using new variable century20th

subset(rd, 
       subset=century20th=='TRUE',       
       select=c("Male.Life.Expectancy", "Female.Life.Expectancy","century20th"))

#EXPLANATION: I've subset the Life expectancy with repsect to century20th variable only with TRUE value in the next cell its with FALSE value
```
```{r}
#Q16 subset with the false value

subset(rd, 
       subset=century20th=='FALSE',       
       select=c("Male.Life.Expectancy", "Female.Life.Expectancy","century20th"))
```
```{r}
#Q17 making new variable which captures centuries

  rd<-rd%>% mutate(rd,century= case_when(Year>=1841 & Year<=1899 ~'18th Century',Year>=1900 & Year<=1999 ~ '19th Century',Year>=2000 & Year<=2083 ~ '20th Century'))

rd
```
```{r}
#18 Creating the Violin Plot

ggplot(rd, aes(x=century,y=Female.Life.Expectancy)) +geom_violin()
```




```{r}
ggplot(rd,aes(x=Male.Life.Expectancy))+ geom_boxplot() + facet_wrap(facets = ~ century)
ggplot(rd,aes(x=Female.Life.Expectancy))+ geom_boxplot() + facet_wrap(facets = ~ century)
```













